---
name: PR Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write  # Allow workflow to post comments on PRs
jobs:
  # Run the actual checks
  pre-commit:
    uses: chaunceyyann/cyan-actions/.github/workflows/reusable-pre-commit.yml@dev
  terraform-lint:
    uses: chaunceyyann/cyan-actions/.github/workflows/reusable-terraform-lint.yml@dev

  # Comment on PR status after checks complete
  comment-status:
    needs: [pre-commit, terraform-lint]
    uses: chaunceyyann/cyan-actions/.github/workflows/reusable-pr-status-commenter.yml@dev
    with:
      required-checks: pre-commit,terraform-lint,python-ci,validate
