name: YAML Validator and S3 Sync

on:
  pull_request:
    branches: [dev, master]
    paths:
      - 'ecp_image_spec/*_image_spec/image_specifications/*.yml'
      - 'ecp_image_spec/*_image_spec/image_specifications/*.yaml'
      - 'ecp_image_spec/*_image_spec/component_specifications/*.yml'
      - 'ecp_image_spec/*_image_spec/component_specifications/*.yaml'
  push:
    branches: [dev, master]
    paths:
      - 'ecp_image_spec/*_image_spec/image_specifications/*.yml'
      - 'ecp_image_spec/*_image_spec/image_specifications/*.yaml'
      - 'ecp_image_spec/*_image_spec/component_specifications/*.yml'
      - 'ecp_image_spec/*_image_spec/component_specifications/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find changed YAML files in image/component_specifications
        id: changed-files
        run: |
          # Determine base branch for PR or push
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^ecp_image_spec/[^/]+_image_spec/(image_specifications|component_specifications)/.*\.ya?ml$' > changed_yaml.txt || true
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^ecp_image_spec/[^/]+_image_spec/(image_specifications|component_specifications)/.*\.ya?ml$' > changed_yaml.txt || true
          fi
          cat changed_yaml.txt

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pyyaml argparse

      - name: Run validator on changed files
        run: |
          if [ -s changed_yaml.txt ]; then
            python container-yaml-validator/validator.py --file $(cat changed_yaml.txt)
          else
            echo "No relevant YAML files changed."
          fi

      - name: Upload Validation Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: '**/*'

  sync-to-s3:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    needs: validate
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          pip install --upgrade pip
          pip install awscli

      - name: Sync image/component_specifications to S3
        run: |
          if [ -z "$S3_BUCKET_NAME" ]; then
            echo "S3_BUCKET_NAME is not set!"
            exit 1
          fi
          aws s3 sync ecp_image_spec/ s3://$S3_BUCKET_NAME/ecp_image_spec/ \
            --exclude "*" \
            --include "*_image_spec/image_specifications/*.yml" \
            --include "*_image_spec/image_specifications/*.yaml" \
            --include "*_image_spec/component_specifications/*.yml" \
            --include "*_image_spec/component_specifications/*.yaml"